//Variável que define as sugestões da input
let suggestions = [
    "Animes",
        "Naruto",
        "Dragon Ball",
        "Darling in the Franxx",
        "My Hero Academia",
        "Boku no Hero Academia",
        "Nanatsu No Taizai",
        "Demon Slayer",
        "Erased",
        "The Promised Neverland",
        "Rent a Girlfriend",
        "Kakegurui",
        "Akame Ga Kill",
        "BNA",
        "Castlevania",
        "Hero Mask",
        "Bleach",
        "Tokyo Goul",
        "One Piece",
        "One Punch Man",
        "Pokémon",
        "Violet Evergarden",
        "Death Note",
        "Fullmetal Alchemist: Brotherhood",
        "Attack on Titan",
        "Shingeki no Kyojin",
        "Kill La Kill",
        "Black Clover",
        "Boruto",
        "Hunter x Hunter",
        "Tower of God",
    "Games",
        "CS:GO",
        "Unturned",
        "Fortnite",
        "Valorant",
        "Rainbow Six",
        "Call Of Duty",
        "Payday 2",
        "FIFA",
        "Minecraft",
        "Phasmophobia",
        "Roblox",
        "Free Fire",
        "Among Us",
        "Standoff 2",
        "PUBG",
        "League of Legends",
        "World of Warcraft",
        "Need For Speed",
        "Hearthstone",
        "Day Z",
        "H1Z1",
        "Rust",
        "Brawlhala",
        "GTA V",
        "MTA",
        "SAMP",
        "Left 4 Dead",
        "Garry's Mod",
        "Watch Dogs",
        "Black Squad",
        "Dota",
        "Apex",
        "Team Fortress 2",
        "Rocket League",
        "Warframe",
        "Destiny 2",
        "Terraria",
        "Counter-Strike",
        "Forza Horizon",
        "Forza Horizon 2",
        "Forza Horizon 3",
        "Forza Horizon 4",
        "Forza Motorsport",
        "Forza Motorsport 2",
        "Forza Motorsport 3",
        "Forza Motorsport 4",
        "Forza Motorsport 5",
        "Forza Motorsport 6",
        "Forza Motorsport 7",
        "Fall Guys",
        "Arma 3",
        "Paladins",
        "Pokémon",
        "Cyberpunk 2077",
        "Watch Dogs 2",
        "Doom Eternal",
        "The Witcher",
        "Shadow Of The Colossus",
        "The Last Of Us",
        "Skyrim",
        "Destiny 2",
        "Apex Legends",
        "Silent Hill",
        "Doom",
        "Assasins Creed",
        "Fifa",
        "PES",
        



    "Vendas",
    "Sales",
    "Donates",
    "Doações",
    "Projetos",
    "Projects",
    "Programação",
    "Programming",
    "Filmes",
    "Movies",
    "Séries",
    "TV Series",
        "Harry Potter",
        "Netflix",
        "La Casa de Papel",
        "Breaking Bad",
    "Entretenimento",
    "Training",
    "Livros",
    "Books",
    "YouTube",
    "Furry",
    "Gatos",
    "Cats",
    "Cachorros",
    "Dogs",
    "Livros",
    "Motivação",
    "Motivation",
    "Conversa casual",
    "Casual Chat",
    "Divulgação",
    "Divulgation",
    "Just Chatting",
    "Apenas Conversando",
    "Pornografia",
    "Porn",
    "Namoro",
    "Dating",
    "Troca de nudes",
    "Nude exchange",
    "Chat",
    "Bored",
    "Entediado",
    "Conversar",
    "Desabafo",
    "Drunk",
    "Zoeira",
    "K-pop",
    "Pop",
    "Rock"
]